/**
 * Delays the execution of a function by the specified amount of time.
 * @param n - The number of milliseconds to delay the execution.
 * @returns A promise that resolves after the specified delay.
 */
export const delay = (n: number) => {
  n = n || 0;
  return new Promise<void>(resolve => {
    setTimeout(() => {
      resolve();
    }, n);
  });
};

/**
 * Generates a random numeric ID.
 *
 * This function is only for simulation purposes and does not generate real, unique IDs.
 * In a real-world application, IDs would be generated by the database or a dedicated ID generator.
 *
 * @returns {number} A random number between 0 and 999999.
 */
export const generateRandomNumericId = () => {
  return Math.floor(Math.random() * 1000000);
};
